version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.django
    restart: on-failure
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "chmod +x /app/start.sh && /app/start.sh"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1010abab
      POSTGRES_USER: course-dog
      POSTGRES_DB: course-dog-db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}