FROM python:3.10

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY coursedog_env /app/coursedog_env

ENV PATH="/app/coursedog_env/bin:$PATH"
ENV PYTHONPATH="/app/coursedog_env/lib/python3.10/site-packages"

COPY . .

RUN chmod +x coursedog_env/bin/activate

RUN /bin/bash -c "source /app/coursedog_env/bin/activate && \
    python manage.py collectstatic --no-input"
